### ISSUE TITLE
[BUG] Wiki里的文章无法操作

### ISSUE THREAD

**Issue by sylar003** [whale4113/cloud-document-converter#10]

**Comment by sylar003** [comment]
不好意思 提bug时因为隐私问题把图片删了，操作步骤确实是点击插件，（保存/下载）都提示无法操作

![image](https://github.com/user-attachments/assets/371d8030-51a9-445f-8d8f-a756638465eb)

**Comment by sylar003** [comment]
其他的飞书网页我试了一下还是正常的

**Comment by whale4113** [comment]
这个文档的文件格式是 PDF 吗？

**Comment by sylar003** [comment]
> 这个文档的文件格式是 PDF 吗？

是Word格式

**Comment by whale4113** [comment]
非常抱歉，目前暂不支持这种文件类型。

**Comment by sylar003** [comment]
感谢~
