### ISSUE TITLE
能不能弄一个Edge的插件

### ISSUE THREAD

**Issue by formoree** [whale4113/cloud-document-converter#11]
一直习惯用Edge，能否弄一个Edge的插件？弄好了一定支持哈哈

**Comment by sylar003** [comment]
你通过Edge打开，基本上所有Chrome的插件都能在Edge中找到，（我就用的Edge）

**Comment by whale4113** [comment]
可以尝试 [从 Chrome Web Store 获取扩展](https://support.microsoft.com/zh-cn/microsoft-edge/%E5%9C%A8-microsoft-edge-%E4%B8%AD%E6%B7%BB%E5%8A%A0-%E5%85%B3%E9%97%AD%E6%88%96%E5%88%A0%E9%99%A4%E6%89%A9%E5%B1%95-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026#ID0EDL)。

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/99a03855-6671-4d90-a2b5-f081eea12ab7">

**Comment by whale4113** [comment]
@formoree 现在，你可以从 [Microsoft Edge 加载项](https://microsoftedge.microsoft.com/addons/detail/pcjebkebnehplnpkpnhipagefaffiopp) 安装此扩展。
