### ISSUE TITLE
后续可以考虑在Edge应用商店上架

### ISSUE THREAD

**Issue by mashxn** [whale4113/cloud-document-converter#19]
插件相当Nice，支持

**Comment by whale4113** [comment]
@mashxn 已在 Microsoft 合作伙伴中心创建并提交扩展，目前扩展状态为审核中，预计最多可能需要 7 个工作日完成审核。

**Comment by whale4113** [comment]
@mashxn 现在，你可以从 [Microsoft Edge 加载项](https://microsoftedge.microsoft.com/addons/detail/pcjebkebnehplnpkpnhipagefaffiopp) 安装此扩展。
