### ISSUE TITLE
请问后续考虑支持包含视频链接的markdown文件下载吗？

### ISSUE THREAD

**Issue by nangongxiaoxin** [whale4113/cloud-document-converter#20]
部分飞书文档的作者会在其中加入视频链接等，如Bilibili的视频。
当前markdown文件下载后，视频块留白，如下：
![2](https://github.com/user-attachments/assets/7e7a5cb4-16cb-4cb0-bac6-52e963707a0f)
希望达成效果：
![1](https://github.com/user-attachments/assets/0a99332c-2847-4aee-bb15-c58f2bfd4963)

**Comment by whale4113** [comment]
@nangongxiaoxin 可以支持

**Comment by whale4113** [comment]
@nangongxiaoxin 在 v1.8.1 中添加了对 iframe 的支持
