### ISSUE TITLE
文档里面如果里面有子文件，也能把子文件下载来就好了

### ISSUE THREAD

**Issue by lynzz** [whale4113/cloud-document-converter#8]
这个小工具真好呀，如果能结合 vitepress 或其他静态服务就太棒了，一键下载下来，再用静态服务部署完美！

**Comment by lujunji4113** [comment]
感谢你提出的这个问题。我们已经解决了该问题，并将在下个版本中发布功能支持。具体来说，我们将在版本 1.6.0 中包含此功能支持。Chrome 插件预计在 1 ~ 2 天内发布。如果你有任何其他问题或建议，请随时在 Issue 中提出。
