### ISSUE TITLE
small modification

### ISSUE THREAD

**Issue by L7132** [whale4113/cloud-document-converter#9]
# Cloud Document Converter

Convert lark cloud documents to markdown.

# Introduction

It is a Chrome extension that supports downloading/copying Lark Doc as Markdown.

[中文文档](./README_ZH.md)

# Features

- Download Lark Doc as Markdown
- 后同

**Comment by L7132** [comment]
我觉得Introduction里面的Cloud Document Converter可以不用加链接了，about里面已给出。

**Comment by whale4113** [comment]
感谢你的建议
